"""
casos_banco_extra.py — Casos adicionales para el banco AntonIA
70 casos extra basados en la biblioteca de doctrina jurídica.
"""
from __future__ import annotations

CASOS_EXTRA: list[dict] = [
    {
        "id": 181, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Promesa de compraventa: requisitos de validez',
        "hechos": 'Rodrigo y Beatriz suscriben un documento privado donde Rodrigo promete venderle un inmueble a Beatriz por $50 millones dentro de 6 meses. El documento no está firmado ante notario ni especifica el plazo exacto de la escritura definitiva.',
        "pregunta": '¿Es válido el contrato de promesa celebrado? ¿Qué requisitos faltan?',
        "respuesta": "El contrato de promesa es válido solo si cumple los cuatro requisitos del art. 1554 CC: (1) que conste por escrito; (2) que el contrato prometido no sea nulo; (3) que contenga un plazo o condición que fije la época de celebración del contrato definitivo; (4) que especifique el contrato prometido de tal manera que solo falten las formalidades. En este caso, falta el requisito del plazo cierto o condición precisa (requisito 3), pues 'dentro de 6 meses' puede no constituir un plazo determinado con precisión. Además, la promesa de compraventa de inmueble no requiere escritura pública per se, pero el contrato prometido sí. La promesa defectuosa no genera obligación de celebrar el contrato definitivo.",
        "fundamento": 'Art. 1554 CC; Abeliuk, Las Obligaciones, T.I',
        "dificultad": 'intermedio',
    },
    {
        "id": 182, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Lesión enorme en compraventa de inmueble',
        "hechos": 'Felipe vende su casa valorada en $120 millones por solo $40 millones a su vecino, quien le presionó invocando deudas urgentes. Felipe quiere rescinder el contrato.',
        "pregunta": '¿Procede la rescisión por lesión enorme? ¿Cuáles son los presupuestos?',
        "respuesta": 'La lesión enorme procede en la compraventa de inmuebles (art. 1888 CC) cuando el precio que recibe el vendedor es inferior a la mitad del justo precio de la cosa vendida, o cuando el precio que paga el comprador es superior al doble del justo precio. En el caso, $40M es inferior a la mitad de $120M ($60M), por lo que hay lesión enorme para el vendedor. El comprador puede optar entre consentir la rescisión o completar el justo precio ($120M menos la décima parte = $108M). Si prefiere la rescisión, se restituyen las prestaciones. La acción prescribe en 4 años desde la fecha del contrato (art. 1896 CC). No procede si el inmueble ha sido enajenado a tercero.',
        "fundamento": 'Arts. 1888-1896 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 183, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Contrato de arrendamiento: mora del arrendatario',
        "hechos": 'La arrendataria Sofía acumula 3 meses de renta impaga. El arrendador Jorge quiere recuperar el inmueble pero Sofía se niega a abandonarlo voluntariamente.',
        "pregunta": '¿Qué acciones tiene Jorge? ¿Cuál es el procedimiento aplicable?',
        "respuesta": 'Jorge puede ejercer la acción de terminación de contrato de arrendamiento por no pago de rentas, conforme al art. 10 de la Ley 18.101. El procedimiento es sumario con reglas especiales. Debe notificarse personalmente al arrendatario. Si el arrendatario no paga dentro del plazo que fija el tribunal, se dicta sentencia de término y lanzamiento. El arrendatario que acredita pago en audiencia puede enervar la acción (art. 10 N°4 Ley 18.101). Si el inmueble tiene destino habitacional, el procedimiento busca proteger al arrendatario vulnerable pero no impide el término por mora grave. Jorge también puede demandar las rentas insolutas.',
        "fundamento": 'Arts. 1942, 1977 CC; Ley 18.101 arts. 10-15',
        "dificultad": 'básico',
    },
    {
        "id": 184, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Mandato: actuación del mandatario fuera de sus poderes',
        "hechos": 'Pedro otorgó mandato a Juan para arrendar su departamento por hasta $600.000 mensuales. Juan, sin consultar, firmó un contrato de arrendamiento por $900.000. El arrendatario Marcos exige cumplimiento del contrato.',
        "pregunta": '¿Está Pedro obligado por el contrato celebrado por Juan? ¿Qué acciones tiene contra Juan?',
        "respuesta": 'Juan actuó extralimitando los poderes del mandato (art. 2160 CC). El mandante no está obligado por actos que excedan los límites del mandato salvo que los ratifique. Pedro puede ratificar el contrato (art. 2160 inc. 2 CC) o rechazarlo. Si lo rechaza, Marcos solo tiene acción contra Juan por los perjuicios que sufra (art. 2154 CC), pues Juan contrató a nombre de Pedro sin poder suficiente. Si Juan alegó tener poderes que no tenía, incurre en responsabilidad personal. Pedro puede además demandar a Juan por los perjuicios causados al exceder el mandato.',
        "fundamento": 'Arts. 2116, 2131, 2154, 2160 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 185, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Condición resolutoria tácita',
        "hechos": 'Ana compró un automóvil a Mario en cuotas. Mario entregó el vehículo pero Ana dejó de pagar desde el tercer mes. Mario quiere recuperar el auto.',
        "pregunta": '¿Qué acciones tiene Mario? ¿Puede exigir resolución y restitución?',
        "respuesta": 'En todo contrato bilateral va envuelta la condición resolutoria tácita (art. 1489 CC): el incumplimiento de una parte da derecho a la otra para pedir la resolución o el cumplimiento del contrato, con indemnización de perjuicios en ambos casos. Mario puede elegir entre: (1) demandar el cumplimiento forzado + perjuicios; o (2) demandar la resolución + perjuicios. Si obtiene resolución, las partes deben restituirse mutuamente: Mario recupera el auto, Ana recupera las cuotas pagadas. Sin embargo, si el vehículo ha sido enajenado a tercero de buena fe, la restitución puede ser imposible (art. 1490 CC).',
        "fundamento": 'Arts. 1489, 1490, 1552 CC',
        "dificultad": 'básico',
    },
    {
        "id": 186, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Nulidad absoluta por objeto ilícito',
        "hechos": 'Luis y Pedro celebran un contrato de compraventa sobre un inmueble embargado judicialmente, sin autorización del juez ni del acreedor. El comprador no sabía del embargo.',
        "pregunta": '¿Cuál es la sanción aplicable a este contrato? ¿Puede el comprador alegar su buena fe?',
        "respuesta": 'La compraventa de cosas embargadas sin autorización judicial adolece de objeto ilícito (art. 1464 N°3 CC), lo que acarrea nulidad absoluta (art. 1682 CC). La nulidad absoluta puede ser declarada de oficio por el juez o alegada por cualquier persona que tenga interés en ello, e incluso por el ministerio público. La buena fe del comprador no sanea el vicio ni impide la nulidad, aunque puede darle derecho a indemnización contra el vendedor. La nulidad absoluta no puede sanearse por ratificación ni prescribe por menos de 10 años (art. 1683 CC).',
        "fundamento": 'Arts. 1462, 1464, 1681, 1682, 1683 CC',
        "dificultad": 'básico',
    },
    {
        "id": 187, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Vicios redhibitorios en compraventa',
        "hechos": 'Claudia compró un automóvil usado. Dos semanas después descubre que el motor tiene fallas graves preexistentes que el vendedor conocía pero no informó.',
        "pregunta": '¿Qué acciones tiene Claudia? ¿Importa que el vendedor conociera los vicios?',
        "respuesta": 'Los vicios redhibitorios dan lugar a la acción redhibitoria (resolución del contrato) o a la acción quanti minoris (rebaja del precio), conforme al art. 1857 CC. Para que sean vicios redhibitorios deben ser: contemporáneos a la venta, graves y ocultos (art. 1858 CC). Si el vendedor conocía los vicios y no los declaró, está de mala fe y responde de la indemnización de perjuicios adicional (art. 1861 CC). Las acciones redhibitoria y quanti minoris prescriben en 6 meses tratándose de bienes muebles (art. 1866 CC). Si el vendedor conocía el vicio, el plazo se extiende a 1 año.',
        "fundamento": 'Arts. 1857-1870 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 188, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Cláusula penal y su reducción judicial',
        "hechos": 'En un contrato de construcción se pactó una multa de $10 millones por cada día de atraso. La obra se retrasó 5 días. El constructor alega que la cláusula es excesiva y equivale al triple del perjuicio real.',
        "pregunta": '¿Puede el juez reducir la cláusula penal? ¿Cuáles son los criterios?',
        "respuesta": 'Sí. Conforme al art. 1544 CC, cuando la obligación principal es determinada el juez puede rebajar la pena en los casos en que fuere manifiestamente excesiva o cuando la obligación principal se ha cumplido en parte. La cláusula penal no puede exceder en más del doble del beneficio que hubiese reportado al acreedor el cumplimiento íntegro y oportuno de la obligación. El tribunal tiene una facultad de morigeración para evitar enriquecimiento injusto. La norma aplica a penas excesivas desproporcionadas al perjuicio real, pero no elimina la cláusula, solo la reduce a límites razonables.',
        "fundamento": 'Arts. 1535-1544 CC; Abeliuk, Las Obligaciones',
        "dificultad": 'avanzado',
    },
    {
        "id": 189, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Contrato de mutuo y reajustabilidad',
        "hechos": 'Banco ABC prestó $10 millones a Teresa con reajuste UF más un 3% anual. Teresa pagó el capital sin reajuste argumentando que la cláusula de reajuste es usuraria.',
        "pregunta": '¿Es válida la cláusula de reajuste? ¿Qué normas regulan el interés máximo convencional?',
        "respuesta": 'Las cláusulas de reajustabilidad son válidas en Chile (art. 1° Ley 18.010). El interés convencional no puede exceder el interés máximo convencional, que equivale al 50% por encima del interés corriente (art. 6 Ley 18.010). Si se pacta un interés superior, se rebaja al máximo convencional. El reajuste en UF no es interés sino actualización del capital al valor de la moneda, por lo que no infringe los límites del interés. Teresa debe pagar el capital reajustado más el 3% anual sobre el capital reajustado. Solo si el interés pactado excede el máximo convencional procede su reducción.',
        "fundamento": 'Arts. 2196-2206 CC; Ley 18.010 arts. 1, 6, 8',
        "dificultad": 'intermedio',
    },
    {
        "id": 190, "rama": 'civil', "subtema": 'Contratos',
        "titulo": 'Contrato por adhesión y cláusulas abusivas',
        "hechos": 'Marcos firmó un contrato de servicios de telefonía con cláusulas preimpresas. Una de ellas permite a la empresa modificar unilateralmente el precio sin aviso previo. Marcos fue cobrado con tarifa aumentada sin notificación.',
        "pregunta": '¿Son válidas las cláusulas que permiten modificación unilateral del precio? ¿Qué norma protege a Marcos?',
        "respuesta": 'Las cláusulas abusivas en contratos de adhesión con consumidores están reguladas por la Ley 19.496 (LPDC). El art. 16 LPDC declara nulas las cláusulas que otorguen al proveedor la facultad de modificar unilateralmente el precio o condiciones del contrato, sin causa justificada o sin notificación previa adecuada. Marcos puede acudir al SERNAC o demandar ante el Juzgado de Policía Local por infracción a la LPDC, solicitando nulidad de la cláusula, restitución del sobrecobro e indemnización. La ley presume la nulidad de tales cláusulas sin necesidad de probar perjuicio específico.',
        "fundamento": 'Ley 19.496 arts. 1, 16, 50 B',
        "dificultad": 'básico',
    },
    {
        "id": 191, "rama": 'civil', "subtema": 'Responsabilidad Extracontractual',
        "titulo": 'Culpa aquiliana y nexo causal',
        "hechos": 'Una empresa constructora dejó un hoyo abierto en la vereda sin señalización. Pedro cae en él de noche y sufre fractura de rodilla. La empresa alega que Pedro debió haber sido más cuidadoso.',
        "pregunta": '¿Concurren los elementos de la responsabilidad extracontractual? ¿Hay culpa de la víctima?',
        "respuesta": 'La responsabilidad extracontractual requiere (art. 2314 CC): hecho ilícito, culpa o dolo del autor, daño y nexo causal. La empresa incurrió en culpa (negligencia) al omitir señalizar el hoyo. Existe nexo causal directo entre la omisión y el daño. Respecto a la culpa de la víctima, si Pedro actuó con la diligencia ordinaria al transitar por una vereda pública, no hay concurrencia de culpas. Pero si tomó riesgos evidentes, puede reducirse la indemnización por culpa concurrente (art. 2330 CC), sin eximirse completamente la empresa de responsabilidad. Pedro puede demandar daño emergente, lucro cesante y daño moral.',
        "fundamento": 'Arts. 2314, 2315, 2329, 2330 CC; Aedo, Culpa Aquiliana',
        "dificultad": 'básico',
    },
    {
        "id": 192, "rama": 'civil', "subtema": 'Responsabilidad Extracontractual',
        "titulo": 'Responsabilidad por hecho ajeno: dependiente',
        "hechos": 'Un conductor de camión de reparto, empleado de una empresa, atropelló a un ciclista por manejar a exceso de velocidad. El ciclista demanda a la empresa.',
        "pregunta": '¿Responde la empresa por el hecho de su empleado? ¿Cuáles son los requisitos?',
        "respuesta": 'Sí. Los arts. 2320 y 2322 CC establecen la responsabilidad del empleador por el hecho culpable de su dependiente cuando este actúa en ejercicio de sus funciones. Los requisitos son: (1) relación de dependencia (subordinación); (2) que el dependiente actúe en el ejercicio de sus funciones o con ocasión de ellas; (3) culpa del dependiente. El empleador responde presuntivamente y solo puede exonerarse probando que actuó con la diligencia debida en la elección y vigilancia del dependiente (culpa in eligendo o in vigilando). La empresa responde solidariamente con el conductor (art. 2317 CC).',
        "fundamento": 'Arts. 2317, 2320, 2322, 2325 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 193, "rama": 'civil', "subtema": 'Responsabilidad Extracontractual',
        "titulo": 'Daño moral: titulares y cuantificación',
        "hechos": 'María muere en un accidente provocado por el dueño de un local que no mantuvo sus instalaciones. Sus hijos adultos y su cónyuge demandan daño moral.',
        "pregunta": '¿Quiénes son titulares de la acción de daño moral por muerte? ¿Cómo se cuantifica?',
        "respuesta": 'El daño moral es reparable en sede extracontractual (art. 2329 CC, interpretación doctrinaria y jurisprudencial). Son titulares los parientes más cercanos que hayan sufrido efectivamente el perjuicio moral: cónyuge e hijos directos tienen legitimación activa reconocida por la jurisprudencia. No se exige acreditar convivencia especial, basta el vínculo familiar. La cuantificación es discrecional del juez, quien considera la intensidad del dolor, el grado de parentesco y las circunstancias. La jurisprudencia ha ido homogeneizando los montos. El daño moral no requiere prueba directa del sufrimiento subjetivo, se presume desde el vínculo y el hecho.',
        "fundamento": 'Arts. 2314, 2329 CC; Aedo, Daño Moral',
        "dificultad": 'intermedio',
    },
    {
        "id": 194, "rama": 'civil', "subtema": 'Responsabilidad Extracontractual',
        "titulo": 'Responsabilidad del Estado por falta de servicio',
        "hechos": 'Un hospital público realizó una operación en forma negligente, provocando daño permanente al paciente. El paciente demanda al Fisco.',
        "pregunta": '¿Bajo qué estatuto responde el Estado? ¿Qué se debe probar?',
        "respuesta": 'La responsabilidad del Estado por falta de servicio está regulada en el art. 38 inc. 2 CPR y los arts. 4 y 42 LOCBGAE (Ley 18.575). La falta de servicio consiste en que el servicio no funciona debiendo funcionar, funciona mal o funciona tardíamente. No se requiere identificar al funcionario culpable: basta la falla del órgano. El demandante debe probar: (1) falta de servicio; (2) daño; (3) nexo causal entre la falta y el daño. La responsabilidad del Estado es directa, no subsidiaria. Se interpone ante los Tribunales ordinarios (no contencioso-administrativo en Chile). El plazo de prescripción es de 4 años.',
        "fundamento": 'Art. 38 CPR; arts. 4, 42 LOCBGAE; Pierry, Responsabilidad Extracontractual del Estado',
        "dificultad": 'avanzado',
    },
    {
        "id": 195, "rama": 'civil', "subtema": 'Responsabilidad Extracontractual',
        "titulo": 'Responsabilidad por productos defectuosos',
        "hechos": 'Carmen compró un calefactor de marca reconocida. El aparato tenía un defecto de fabricación que produjo un incendio en su casa. El fabricante alega que el producto fue instalado incorrectamente.',
        "pregunta": '¿Responde el fabricante por el producto defectuoso? ¿Qué debe probar Carmen?',
        "respuesta": 'En Chile, la responsabilidad por productos defectuosos se rige por la Ley 19.496 (LPDC) y el Código Civil. La LPDC establece responsabilidad solidaria del fabricante, importador y vendedor. Carmen debe probar: (1) defecto del producto; (2) daño; (3) nexo causal. No requiere probar culpa del fabricante si aplica el estatuto de la LPDC. El fabricante puede eximirse si prueba que el defecto se produjo por uso indebido o instalación incorrecta por el consumidor. La carga probatoria de la exención es del fabricante. También procede la acción ex art. 2314 CC si se acredita culpa.',
        "fundamento": 'Ley 19.496 arts. 20, 23; art. 2314 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 196, "rama": 'civil', "subtema": 'Bienes y Derechos Reales',
        "titulo": 'Prescripción adquisitiva ordinaria de inmueble',
        "hechos": 'Jorge posee un terreno en forma pública, pacífica e ininterrumpida durante 5 años, con justo título y buena fe. El propietario registral se opone.',
        "pregunta": '¿Ha adquirido Jorge el dominio por prescripción? ¿Qué se requiere?',
        "respuesta": 'La prescripción adquisitiva ordinaria de inmuebles requiere posesión regular durante 5 años (art. 2508 CC). La posesión regular exige justo título, buena fe inicial y tradición si el título lo requiere (art. 702 CC). Si Jorge cumple estos requisitos, puede demandar la prescripción adquisitiva ante el tribunal civil, lo que extingue el dominio del anterior propietario y lo radica en Jorge. La sentencia se inscribe en el Conservador de Bienes Raíces para producir efectos frente a terceros. La posesión inscrita requiere inscripción conservatoria para ampararse en la prescripción (art. 924 CC).',
        "fundamento": 'Arts. 700, 702, 2492, 2506-2510 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 197, "rama": 'civil', "subtema": 'Bienes y Derechos Reales',
        "titulo": 'Servidumbre de tránsito',
        "hechos": 'El fundo de Ana quedó encerrado sin salida a la vía pública tras la subdivisión del predio vecino de Pedro. Ana necesita paso para acceder a su propiedad.',
        "pregunta": '¿Puede Ana exigir una servidumbre de tránsito? ¿Qué requisitos debe cumplir?',
        "respuesta": 'Sí. El art. 847 CC establece que si un predio se halla destituido de todo salida a la vía pública, el dueño tiene derecho a exigir una servidumbre de paso por los predios vecinos. Los requisitos son: (1) fundo encerrado sin salida; (2) necesidad real; (3) indemnización al dueño del predio sirviente. El paso debe ser por el lugar que cause menor perjuicio al predio sirviente. La servidumbre es legal y no puede ser denegada. Ana debe pagar indemnización a Pedro. Si no hay acuerdo, fija el monto el tribunal.',
        "fundamento": 'Arts. 820, 847-860 CC',
        "dificultad": 'básico',
    },
    {
        "id": 198, "rama": 'civil', "subtema": 'Bienes y Derechos Reales',
        "titulo": 'Acción reivindicatoria: requisitos',
        "hechos": 'Valeria es dueña registral de un inmueble que actualmente ocupa Diego sin título alguno. Diego lleva 2 años en el inmueble.',
        "pregunta": '¿Puede Valeria ejercer la acción reivindicatoria? ¿Qué debe probar?',
        "respuesta": 'La acción reivindicatoria (art. 889 CC) protege el dominio del propietario que ha perdido la posesión. Valeria debe probar: (1) que es dueña del inmueble (dominio); (2) que Diego posee actualmente el bien; (3) identidad de la cosa reivindicada. Como Diego solo lleva 2 años y la prescripción ordinaria de inmuebles requiere 5, aún no ha adquirido el dominio. Valeria puede demandar la restitución del inmueble y los frutos percibidos durante la posesión de mala fe. Diego, como poseedor de mala fe, debe restituir los frutos y no tiene derecho a mejoras voluptuarias.',
        "fundamento": 'Arts. 889-915 CC',
        "dificultad": 'básico',
    },
    {
        "id": 199, "rama": 'civil', "subtema": 'Bienes y Derechos Reales',
        "titulo": 'Hipoteca: preferencia y ejecución',
        "hechos": 'Banco ABC tiene hipoteca de primer grado sobre la casa de Roberto. Roberto no paga el crédito hipotecario. Un segundo acreedor tiene una hipoteca de segundo grado.',
        "pregunta": '¿Cómo opera la preferencia hipotecaria? ¿Qué sucede con el segundo hipotecario?',
        "respuesta": 'La hipoteca confiere al acreedor hipotecario el derecho real de persecución de la finca (art. 2428 CC) y un crédito privilegiado de segunda clase (art. 2477 CC) que se ejerce sobre el producto del remate. El acreedor de primer grado tiene preferencia sobre el de segundo. En la ejecución, el producto del remate se distribuye: primero se pagan las costas, luego el primer hipotecario hasta cubrir su crédito, y si hay remanente, el segundo hipotecario. Si el producto no alcanza para el segundo, este puede perseguir otros bienes del deudor como acreedor valista. El acreedor hipotecario puede sacar la finca a remate hipotecario.',
        "fundamento": 'Arts. 2407, 2428, 2477 CC; CPC arts. 490 ss.',
        "dificultad": 'avanzado',
    },
    {
        "id": 200, "rama": 'civil', "subtema": 'Bienes y Derechos Reales',
        "titulo": 'Modos de adquirir: accesión de inmueble a inmueble',
        "hechos": 'El río desborda y deposita sedimentos en el predio de Ana, aumentando su superficie en 200 m2. El predio vecino de Luis pierde esos 200 m2 de tierra.',
        "pregunta": '¿A quién pertenecen los terrenos depositados por el río? ¿Puede Luis reclamarlos?',
        "respuesta": 'Conforme al art. 650 CC, el aluvión (aumento de tierra producido por el lento e imperceptible retiro de las aguas) pertenece al dueño del terreno ribereño. Como el depósito se produce en el predio de Ana, ella adquiere por accesión natural la tierra añadida. Luis pierde la tierra de su predio que fue arrastrada. Si el depósito es repentino por avenida u otra fuerza destructora, se aplican reglas distintas (avulsión, art. 652 CC), en cuyo caso el dueño puede reclamarla dentro de un año. Pero si es aluvión gradual, el cambio de fronteras es definitivo y Luis no puede reclamarlos.',
        "fundamento": 'Arts. 588, 649, 650, 652 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 201, "rama": 'civil', "subtema": 'Obligaciones',
        "titulo": 'Solidaridad pasiva y sus efectos',
        "hechos": 'Ana, Bruno y Carlos son codeudores solidarios de una deuda de $9 millones con el banco. Bruno es insolvente. El banco cobra la totalidad a Ana.',
        "pregunta": '¿Puede el banco cobrar el total a Ana? ¿Qué acción tiene Ana contra los otros?',
        "respuesta": 'Sí. En la solidaridad pasiva cada deudor está obligado al total (art. 1511 CC). El acreedor puede dirigirse contra cualquiera de los deudores solidarios por el total de la deuda. Ana, al pagar el total ($9M), se subroga en los derechos del banco (art. 1522 CC) y puede exigir a Carlos su cuota ($3M). Respecto de Bruno (insolvente), la cuota que le corresponde se distribuye entre Ana y Carlos por partes iguales (art. 1522 inc. 2 CC). Así Ana puede cobrar a Carlos $3M + $1,5M (mitad de la cuota de Bruno) = $4,5M en total.',
        "fundamento": 'Arts. 1511, 1514, 1522 CC; Abeliuk, Las Obligaciones T.I',
        "dificultad": 'avanzado',
    },
    {
        "id": 202, "rama": 'civil', "subtema": 'Obligaciones',
        "titulo": 'Novación: requisitos y efectos',
        "hechos": 'Pedro debe $5 millones a Juan. Ambos acuerdan que la deuda quede extinguida y que Pedro quede obligado a ejecutar una obra de construcción para Juan.',
        "pregunta": '¿Hay novación? ¿Cuáles son sus efectos sobre la obligación primitiva?',
        "respuesta": 'Sí hay novación objetiva por cambio de objeto (art. 1628 CC). Los requisitos de la novación son: (1) existencia de una obligación anterior válida; (2) una nueva obligación; (3) diferencia esencial entre ambas; (4) intención de novar (animus novandi). Al celebrarse la novación, la obligación primitiva se extingue con todos sus accesorios (cauciones, privilegios, intereses) salvo que las partes los reserven expresamente. Desde entonces solo existe la nueva obligación (la de construir). Si Juan no puede cobrar lo pactado, no puede retrotraerse a la obligación primitiva ya extinguida.',
        "fundamento": 'Arts. 1628-1645 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 203, "rama": 'civil', "subtema": 'Obligaciones',
        "titulo": 'Compensación legal de deudas',
        "hechos": 'Ana debe a Bruno $3 millones por un préstamo. Bruno debe a Ana $2 millones por concepto de arriendo. Ambas deudas son líquidas y exigibles. Ana quiere oponer compensación.',
        "pregunta": '¿Procede la compensación? ¿Qué efecto produce?',
        "respuesta": 'Procede la compensación legal (art. 1655 CC) cuando ambas partes son recíprocamente deudoras de cantidades de dinero (o de cosas fungibles de igual género) que sean actualmente exigibles, líquidas y no sujetas a plazo ni condición. En el caso, ambas deudas son dinerarias, líquidas y exigibles, por lo que la compensación opera de pleno derecho (art. 1656 CC) hasta la concurrencia del monto menor ($2M). Ana solo debe a Bruno $1 millón (diferencia). La compensación extingue ambas deudas hasta el menor valor, sin necesidad de sentencia judicial.',
        "fundamento": 'Arts. 1655-1664 CC',
        "dificultad": 'básico',
    },
    {
        "id": 204, "rama": 'civil', "subtema": 'Obligaciones',
        "titulo": 'Prescripción extintiva de acción ordinaria',
        "hechos": 'María sufrió un accidente de tránsito en enero de 2019 y fue indemnizada solo parcialmente. Quiere demandar en enero de 2025 los perjuicios pendientes.',
        "pregunta": '¿Está prescrita la acción de indemnización de perjuicios extracontractual?',
        "respuesta": 'La acción de responsabilidad extracontractual prescribe en 4 años desde la perpetración del acto (art. 2332 CC). El accidente ocurrió en enero de 2019, por lo que la prescripción se cumplió en enero de 2023. En enero de 2025 ya ha transcurrido el plazo de 4 años, por lo que la acción estaría prescrita. Sin embargo, si hubo reconocimiento de la deuda por el deudor o una interrupción natural o civil de la prescripción (art. 2518 CC), el plazo se cuenta desde el último acto interruptivo. La prescripción extintiva debe ser alegada por el demandado; el juez no puede declararla de oficio.',
        "fundamento": 'Arts. 2514, 2515, 2518, 2332 CC',
        "dificultad": 'básico',
    },
    {
        "id": 205, "rama": 'civil', "subtema": 'Obligaciones',
        "titulo": 'Buena fe contractual y deber de información',
        "hechos": 'Una empresa inmobiliaria vendió departamentos ocultando que el edificio tenía problemas estructurales conocidos. Los compradores descubren el problema años después.',
        "pregunta": '¿Infringe la inmobiliaria el principio de buena fe? ¿Qué acciones tienen los compradores?',
        "respuesta": 'La buena fe contractual (art. 1546 CC) impone a las partes un deber de conducta leal durante toda la ejecución del contrato, incluyendo la etapa precontractual. El dolo por omisión (reticencia dolosa) consiste en callar intencionalmente hechos relevantes que la otra parte habría querido conocer. Conocer el defecto y no informarlo constituye dolo (art. 1458 CC). Los compradores tienen acción de nulidad relativa por vicios del consentimiento (dolo determinante) o acción redhibitoria por vicios ocultos graves. Además, si hay dolo, procede indemnización plena incluyendo el lucro cesante.',
        "fundamento": 'Arts. 1458, 1546, 1857, 1861 CC; De la Maza, Buena Fe y Dolo por Omisión',
        "dificultad": 'avanzado',
    },
    {
        "id": 206, "rama": 'penal', "subtema": 'Teoría del Delito',
        "titulo": 'Iter criminis: tentativa y frustración',
        "hechos": 'Manuel intentó robar una joyería. Fue detenido por carabineros cuando ya había forzado la puerta trasera y estaba dentro del local con el botín en manos pero aún no había salido del inmueble.',
        "pregunta": '¿En qué etapa del iter criminis se encontraba Manuel? ¿Tentativa o delito frustrado?',
        "respuesta": 'El art. 7 CP distingue: delito consumado (acción ejecutada completa), frustrado (el delincuente pone todo lo necesario de su parte pero no se produce el resultado por causas ajenas a su voluntad) y tentativa (el culpable da principio a la ejecución por hechos directos pero falta la ejecución completa). Manuel ya tenía el botín en sus manos, lo que podría configurar delito frustrado de robo, pues realizó todos los actos ejecutivos pero fue detenido antes de consumar. La jurisprudencia chilena discute si el robo se consuma al aprehender la cosa o al salir del lugar. Si se sigue la tesis de la ablatio, no había consumación. Frustrado tiene pena menor que el consumado.',
        "fundamento": 'Art. 7 CP; Etcheberry, Derecho Penal Parte General T.I',
        "dificultad": 'intermedio',
    },
    {
        "id": 207, "rama": 'penal', "subtema": 'Teoría del Delito',
        "titulo": 'Estado de necesidad justificante',
        "hechos": 'Ana destruyó la puerta del auto de su vecino para extraer a un niño que quedó encerrado en pleno verano con riesgo de muerte. El vecino la denuncia por daños.',
        "pregunta": '¿Puede Ana invocar el estado de necesidad? ¿Cuáles son sus requisitos?',
        "respuesta": 'El estado de necesidad justificante (art. 10 N°7 CP) exime de responsabilidad cuando: (1) se ejecuta un hecho para evitar un mal mayor; (2) el mal que se inflige es menor al que se trata de evitar; (3) no hay otro medio practicable y menos perjudicial; (4) el sujeto no es el causante de la situación de peligro. En el caso, el daño a la puerta (mal menor) evitó la muerte del niño (mal mayor). No había otro medio práctico e inmediato. Ana no causó el encierro. Concurren todos los requisitos del estado de necesidad, por lo que la acción está justificada y Ana no es punible.',
        "fundamento": 'Art. 10 N°7 CP; Cury, Derecho Penal',
        "dificultad": 'básico',
    },
    {
        "id": 208, "rama": 'penal', "subtema": 'Teoría del Delito',
        "titulo": 'Legítima defensa propia',
        "hechos": 'Pedro fue atacado de noche en la calle por un desconocido armado con cuchillo que exigió su billetera. Pedro tenía un gas pimienta y lo utilizó, lesionando al atacante.',
        "pregunta": '¿Puede Pedro invocar legítima defensa? ¿Cuáles son los requisitos?',
        "respuesta": 'La legítima defensa propia (art. 10 N°4 CP) requiere: (1) agresión ilegítima; (2) necesidad racional del medio empleado para impedirla o repelerla; (3) falta de provocación suficiente por parte del defensor. (1) El ataque armado nocturno es agresión ilegítima actual. (2) El gas pimienta como medio defensivo contra un atacante con cuchillo es racionalmente necesario y proporcional. (3) Pedro no provocó el ataque. Concurren todos los requisitos. Pedro actúa en legítima defensa y no es punible. Si la defensa fuera excesiva (matar al atacante), podría haber exceso en la defensa con atenuante.',
        "fundamento": 'Art. 10 N°4 CP; Politoff, Matus y Ramírez, Lecciones',
        "dificultad": 'básico',
    },
    {
        "id": 209, "rama": 'penal', "subtema": 'Teoría del Delito',
        "titulo": 'Imputabilidad: inimputabilidad por enajenación mental',
        "hechos": 'Carlos, diagnosticado con esquizofrenia paranoide, agredió a su vecino durante un episodio psicótico grave. Al momento del hecho, no comprendía la ilicitud de su conducta.',
        "pregunta": '¿Es Carlos imputable? ¿Qué consecuencias jurídico-penales se aplican?',
        "respuesta": 'Carlos es inimputable (art. 10 N°1 CP): el loco o demente, a no ser que haya obrado en un intervalo lúcido, está exento de responsabilidad criminal. Al no poder comprender la ilicitud del acto ni motivarse por la norma durante el episodio psicótico, falta la imputabilidad (capacidad de culpabilidad). No se aplica pena pero sí pueden imponerse medidas de seguridad: internación en un establecimiento psiquiátrico (art. 455 CPP) si hay peligro para sí mismo o terceros. El tribunal penal debe decretar el sobreseimiento definitivo por inimputabilidad.',
        "fundamento": 'Art. 10 N°1 CP; arts. 455-465 CPP; Náquira, Derecho Penal Chileno',
        "dificultad": 'intermedio',
    },
    {
        "id": 210, "rama": 'penal', "subtema": 'Teoría del Delito',
        "titulo": 'Concurso real de delitos y penalidad',
        "hechos": 'Juan cometió en una sola semana: un robo con intimidación, una estafa y un delito de manejo en estado de ebriedad. El fiscal acusa por los tres delitos.',
        "pregunta": '¿Cómo se castiga la pluralidad de delitos? ¿Qué sistema de penas aplica Chile?',
        "respuesta": 'Chile adopta el sistema de acumulación aritmética moderada para el concurso real (art. 74 CP): se impone al culpable todas las penas correspondientes a los diversos crímenes o simples delitos, salvo que las disposiciones de la ley apliquen solo la pena mayor. Las penas se cumplen sucesivamente comenzando por la más grave (art. 74 CP). Sin embargo, si la aplicación del art. 74 resulta más perjudicial que el art. 75 (concurso ideal), se aplica el más favorable. Para el concurso real, el juez puede acumular materialmente las penas, lo que puede resultar en penas muy elevadas. El fiscal debe distinguir si los delitos tienen autonomía entre sí.',
        "fundamento": 'Arts. 74, 75 CP; Etcheberry, Derecho Penal Parte General T.II',
        "dificultad": 'avanzado',
    },
    {
        "id": 211, "rama": 'penal', "subtema": 'Delitos Patrimoniales',
        "titulo": 'Robo con fuerza en las cosas en lugar habitado',
        "hechos": 'Dos sujetos ingresaron de noche a una casa usando llaves falsas, sustrajeron joyas y electrónicos. Los dueños estaban durmiendo en el interior.',
        "pregunta": '¿Qué delito configura esta conducta? ¿Por qué es más grave que el hurto?',
        "respuesta": 'Configura robo con fuerza en las cosas en lugar habitado (art. 440 CP), que sanciona con presidio mayor en su grado mínimo. El uso de llaves falsas es uno de los medios de fuerza sobre la cosa que tipifica el delito (art. 440 N°1 CP). Es más grave que el hurto porque: (1) se invade la morada (derecho a la inviolabilidad del hogar); (2) se usan medios especiales de comisión; (3) crea mayor alarma social. La pena es superior a la del robo en lugar no habitado. La habitación al momento del hecho agrava aún más el injusto por el peligro potencial para las personas.',
        "fundamento": 'Arts. 432, 440 CP; Oliver, Estructura Típica del Hurto y Robo',
        "dificultad": 'básico',
    },
    {
        "id": 212, "rama": 'penal', "subtema": 'Delitos Patrimoniales',
        "titulo": 'Estafa: el engaño como elemento típico',
        "hechos": "Roberto se hizo pasar por un funcionario del SII y llamó por teléfono a comerciantes ofreciendo 'regularizar deudas' previo pago de $200.000. Varios pagaron.",
        "pregunta": '¿Configura estafa esta conducta? ¿Cuáles son los elementos típicos exigidos?',
        "respuesta": 'La estafa (art. 468 CP) requiere: (1) engaño (conducta mendaz que genera una representación falsa de la realidad); (2) error en la víctima (la representación falsa determina su voluntad); (3) disposición patrimonial perjudicial (acto económico causado por el error); (4) perjuicio patrimonial; (5) ánimo de lucro. Roberto empleó engaño activo (simulación de identidad), generó error en las víctimas (creyeron regularizar deudas reales), y estas realizaron la disposición patrimonial ($200.000 cada una). Hay perjuicio y ánimo de lucro. Todos los elementos concurren: es estafa del art. 468 CP, con pena de presidio menor.',
        "fundamento": 'Arts. 468, 473 CP; Mayer, La Estafa como Delito Económico; Hernández, Normativización del Engaño',
        "dificultad": 'intermedio',
    },
    {
        "id": 213, "rama": 'penal', "subtema": 'Delitos contra las Personas',
        "titulo": 'Homicidio simple vs. calificado: el dolo',
        "hechos": 'Carlos disparó a su cuñado en una discusión familiar después de haber planeado el ataque durante dos días, comprado el arma y esperado el momento en que la víctima estuviera sola.',
        "pregunta": '¿Es homicidio simple o calificado? ¿Qué elemento diferencia ambas figuras?',
        "respuesta": 'Es homicidio calificado (art. 391 N°1 CP), específicamente con la circunstancia de premeditación conocida. La premeditación supone: (1) resolución de matar adoptada con anterioridad; (2) persistencia en esa resolución durante cierto tiempo; (3) frialdad de ánimo durante la reflexión. Carlos planeó el ataque durante dos días, compró el arma y esperó la ocasión: concurren todos los elementos de la premeditación. El homicidio calificado tiene pena de presidio mayor en su grado medio a presidio perpetuo. El homicidio simple (art. 391 N°2) sanciona el matar sin estas circunstancias calificantes.',
        "fundamento": 'Art. 391 CP; Garrido Montt, Derecho Penal T.III',
        "dificultad": 'intermedio',
    },
    {
        "id": 214, "rama": 'penal', "subtema": 'Delitos Funcionarios',
        "titulo": 'Malversación de caudales públicos',
        "hechos": 'El tesorero municipal Manuel utilizó fondos públicos de $30 millones para pagar deudas personales. Luego devolvió la mitad pero no el resto.',
        "pregunta": '¿Qué delito comete Manuel? ¿La devolución parcial atenúa la responsabilidad?',
        "respuesta": 'Manuel comete malversación de caudales públicos (art. 233 CP): el empleado público que, teniendo a su cargo caudales o efectos públicos o de particulares en depósito, consignación u otro título que produzca obligación de entregar o devolver, los sustrajere o consintiere que otro los sustraiga. La pena varía según el monto (art. 233 N°1, 2, 3 CP). La devolución posterior no extingue el delito pero puede configurar la atenuante de reparación (art. 11 N°7 CP) si es oportuna. Jurisprudencialmente, la restitución total oportuna puede llevar a la atenuante muy calificada, pero la parcial no extingue la responsabilidad penal.',
        "fundamento": 'Arts. 233, 235 CP; Hernández, Enriquecimiento Ilícito de Funcionarios',
        "dificultad": 'avanzado',
    },
    {
        "id": 215, "rama": 'penal', "subtema": 'Delitos Funcionarios',
        "titulo": 'Cohecho activo: el que corrompe',
        "hechos": 'Un empresario ofreció $5 millones a un inspector municipal para que no notificara una infracción sanitaria en su establecimiento. El inspector aceptó.',
        "pregunta": '¿Comete delito el empresario? ¿Y el inspector? ¿Son delitos distintos?',
        "respuesta": 'Sí, ambos cometen delito pero distinto. El inspector comete cohecho pasivo (art. 248 CP): el empleado público que solicitare o aceptare recibir mayores derechos de los que le están señalados por razón de su oficio o admitiere promesa ilegítima. El empresario comete cohecho activo (art. 250 CP): el que ofreciere o consintiere dar a un empleado público un beneficio económico a fin de que realice u omita un acto de su cargo. Son tipos penales autónomos que pueden concurrir simultáneamente. Las reformas recientes de la Ley 21.121 agravaron las penas del cohecho en Chile.',
        "fundamento": 'Arts. 248, 250 CP; Mañalich, Cohecho como Propuesta o Aceptación',
        "dificultad": 'avanzado',
    },
    {
        "id": 216, "rama": 'procesal', "subtema": 'Proceso Civil',
        "titulo": 'Demanda: requisitos y consecuencias de la omisión',
        "hechos": 'Diego presentó una demanda de cobro de dinero sin indicar el procedimiento aplicable y sin acompañar los documentos fundantes. El tribunal la rechazó por inadmisible.',
        "pregunta": '¿Cuáles son los requisitos formales de la demanda? ¿Qué sucede si faltan?',
        "respuesta": 'Los requisitos de la demanda están en el art. 254 CPC: (1) designación del tribunal; (2) nombre, domicilio y profesión del demandante y demandado; (3) exposición clara de los hechos y fundamentos de derecho; (4) enumeración precisa y clara de las peticiones. Si la demanda no contiene las designaciones de los números 1, 2 o 3, el tribunal puede no darle curso de oficio, ordenando que se subsanen los defectos (art. 256 CPC). No procede rechazo in limine salvo vicio muy grave. El tribunal debe dar un plazo para subsanar. Si no se corrige, puede declararse inadmisible.',
        "fundamento": 'Arts. 253, 254, 256 CPC; Casarino, Manual de Derecho Procesal Civil',
        "dificultad": 'básico',
    },
    {
        "id": 217, "rama": 'procesal', "subtema": 'Proceso Civil',
        "titulo": 'Excepciones dilatorias: la incompetencia absoluta',
        "hechos": 'Una empresa demanda a otra por $500 millones en un Juzgado de Policía Local, aduciendo que allí es más rápido. La demandada opone excepción de incompetencia.',
        "pregunta": '¿Cuándo procede la excepción dilatoria de incompetencia? ¿Absoluta o relativa?',
        "respuesta": 'El Juzgado de Policía Local solo tiene competencia para asuntos de menor cuantía y materias especiales (Ley 18.287). Una causa de $500 millones corresponde al Tribunal Civil competente según cuantía y territorio. La incompetencia puede ser absoluta (materia, fuero, grado) o relativa (territorio). La incompetencia absoluta puede alegarse en cualquier momento del proceso como excepción o de oficio por el tribunal. La relativa solo como excepción dilatoria en primera instancia antes de la litis contestación (art. 303 N°1 CPC). En este caso hay incompetencia absoluta por razón de materia, que el tribunal debería declarar incluso de oficio.',
        "fundamento": 'Arts. 101-116 COT; arts. 303, 305 CPC',
        "dificultad": 'intermedio',
    },
    {
        "id": 218, "rama": 'procesal', "subtema": 'Proceso Civil',
        "titulo": 'Medida cautelar: secuestro de bienes muebles',
        "hechos": 'Valeria teme que el deudor Pedro venda su automóvil antes del juicio para evitar el pago. Quiere asegurar el resultado del proceso.',
        "pregunta": '¿Puede Valeria solicitar el secuestro del auto? ¿Cuáles son los requisitos?',
        "respuesta": 'El secuestro (art. 291 CPC) procede cuando la acción entablada tiene por objeto reivindicar bienes muebles o cuando se discute el dominio o posesión de cosa mueble y hay motivo de temer su pérdida o deterioro. Si la acción es de cobro de dinero, la medida precautoria adecuada es el embargo preventivo (art. 290 CPC) o la prohibición de celebrar actos y contratos (art. 290 N°3). Valeria debe acreditar: (1) fumus boni iuris (apariencia de buen derecho); (2) periculum in mora (peligro en la demora: que Pedro venda o deteriore el bien). Debe rendirse caución si el juez lo exige (art. 298 CPC).',
        "fundamento": 'Arts. 290-302 CPC',
        "dificultad": 'intermedio',
    },
    {
        "id": 219, "rama": 'procesal', "subtema": 'Proceso Civil',
        "titulo": 'Recurso de apelación: efectos',
        "hechos": 'El tribunal de primera instancia condena a Mario a pagar $5 millones. Mario apela y pide que la apelación se conceda en ambos efectos para no tener que pagar mientras se resuelve.',
        "pregunta": '¿Cuándo se concede la apelación en ambos efectos? ¿Qué efecto suspensivo implica?',
        "respuesta": 'El recurso de apelación puede concederse en el solo efecto devolutivo o en ambos efectos (devolutivo y suspensivo). La regla general es que la apelación de sentencias definitivas se concede en ambos efectos (art. 195 CPC), lo que suspende la ejecución de la sentencia hasta el fallo de la apelación. Las sentencias interlocutorias y los autos generalmente se conceden en el solo efecto devolutivo, sin suspender la ejecución. En el caso, la sentencia definitiva de primera instancia se apela en ambos efectos, por lo que Mario no debe pagar hasta que la Corte de Apelaciones resuelva el recurso.',
        "fundamento": 'Arts. 194, 195, 239 CPC',
        "dificultad": 'básico',
    },
    {
        "id": 220, "rama": 'procesal', "subtema": 'Proceso Civil',
        "titulo": 'Cosa juzgada: triple identidad',
        "hechos": 'Ana demandó a Bruno por $1 millón por concepto de préstamo. El tribunal rechazó la demanda. Ana vuelve a demandar a Bruno por el mismo $1 millón argumentando nuevos antecedentes.',
        "pregunta": '¿Puede Ana volver a demandar? ¿Cuándo opera la excepción de cosa juzgada?',
        "respuesta": "La cosa juzgada (art. 175 CPC) impide que una misma controversia sea nuevamente conocida por los tribunales cuando hay triple identidad: (1) mismas partes (Ana y Bruno); (2) misma cosa pedida ($1 millón); (3) misma causa de pedir (el mismo préstamo). Si concurre la triple identidad, la excepción de cosa juzgada (art. 310 CPC) es perentoria y enerva la nueva demanda. Si Ana alega 'nuevos antecedentes', debe verificarse si la causa de pedir es distinta. La cosa juzgada puede alegarse como excepción en cualquier estado de la causa (art. 310 CPC).",
        "fundamento": 'Arts. 175-177, 310 CPC',
        "dificultad": 'básico',
    },
    {
        "id": 221, "rama": 'constitucional', "subtema": 'Garantías Constitucionales',
        "titulo": 'Recurso de amparo: procedencia y plazo',
        "hechos": 'Luis fue arrestado por carabineros sin orden judicial y lleva 48 horas detenido sin ser puesto a disposición del juez. Su familia quiere una acción urgente.',
        "pregunta": '¿Qué acción constitucional procede? ¿Ante qué tribunal y en qué plazo?',
        "respuesta": 'Procede el recurso de amparo (habeas corpus), consagrado en el art. 21 CPR. Protege la libertad personal y seguridad individual frente a detenciones ilegales o arbitrarias. Lo puede interponer el propio afectado o cualquier persona a su nombre, en cualquier momento, ante la Corte de Apelaciones respectiva. No tiene plazo para interponerse. La Corte puede ordenar de inmediato que el individuo sea traído a su presencia (auto de comparendo), verificar la legalidad de la detención y ordenar la libertad o el envío al tribunal competente. La detención sin control judicial dentro de 24 horas es ilegal (art. 19 N°7 CPR).',
        "fundamento": 'Art. 21 CPR; art. 19 N°7 CPR',
        "dificultad": 'básico',
    },
    {
        "id": 222, "rama": 'constitucional', "subtema": 'Garantías Constitucionales',
        "titulo": 'Recurso de protección: actos u omisiones arbitrarias',
        "hechos": 'Una municipalidad cortó el suministro de agua a un campamento informal sin previo aviso ni justificación, afectando a 200 familias.',
        "pregunta": '¿Procede recurso de protección? ¿Qué garantías estarían afectadas?',
        "respuesta": 'El recurso de protección (art. 20 CPR) procede frente a actos u omisiones arbitrarios o ilegales que afecten los derechos del art. 19 CPR protegidos por la acción. La falta de agua puede afectar: (1) el derecho a la vida (art. 19 N°1); (2) el derecho a la integridad física (art. 19 N°1); (3) el derecho a vivir en un medio libre de contaminación (art. 19 N°8). Si la municipalidad actuó sin fundamento y sin debido proceso, el acto es arbitrario. Se interpone ante la CA del domicilio del afectado dentro de 30 días desde que se tuvo noticia o ejecutó el acto. La CA puede ordenar restablecer el derecho.',
        "fundamento": 'Art. 20 CPR; arts. 19 N°1, 8 CPR; Auto Acordado Corte Suprema',
        "dificultad": 'intermedio',
    },
    {
        "id": 223, "rama": 'constitucional', "subtema": 'Garantías Constitucionales',
        "titulo": 'Derecho de propiedad: expropiación y justa indemnización',
        "hechos": 'El Estado decretó la expropiación del predio de Ana para construir una autopista. Le ofrecen el avalúo fiscal que es la mitad del valor comercial del predio.',
        "pregunta": '¿Tiene derecho Ana a una indemnización mayor? ¿Cómo se reclama?',
        "respuesta": 'El art. 19 N°24 CPR garantiza el derecho de propiedad y exige que la expropiación sea autorizada por ley y que el expropiado reciba justa indemnización por el daño patrimonial efectivamente causado. La indemnización debe ser el valor comercial del bien (no el avalúo fiscal), incluyendo el daño emergente y el lucro cesante. Ana puede reclamar el monto de la indemnización ante los Tribunales ordinarios dentro del plazo legal (art. 19 N°24 inc. 3 CPR). El reclamo suspende la toma de posesión si el expropiado no ha recibido la indemnización provisional.',
        "fundamento": 'Art. 19 N°24 CPR; Ley 16.640; DL 2186',
        "dificultad": 'avanzado',
    },
    {
        "id": 224, "rama": 'constitucional', "subtema": 'Control de Constitucionalidad',
        "titulo": 'Inaplicabilidad por inconstitucionalidad: legitimación activa',
        "hechos": 'Durante un juicio civil, Pedro alega que el art. 1464 N°4 CC (cosas en litigio) es inconstitucional porque viola el derecho de propiedad al prohibir la enajenación de bienes litigiosos.',
        "pregunta": '¿Puede Pedro plantear esta alegación? ¿Ante qué tribunal y en qué momento?',
        "respuesta": 'Pedro puede interponer recurso de inaplicabilidad por inconstitucionalidad ante el Tribunal Constitucional (art. 93 N°6 CPR). El TC puede declarar inaplicable un precepto legal cuya aplicación en la gestión resulte contraria a la Constitución. Legitimados activos: cualquiera de las partes o el juez de oficio. Debe presentarse mientras el juicio esté pendiente. El TC analizará si la aplicación del precepto en ese caso concreto (no en abstracto) vulnera la CPR. Si acoge el recurso, el precepto no se aplica en ese juicio, pero sigue vigente para otros casos.',
        "fundamento": 'Art. 93 N°6 CPR; Ley Orgánica del TC',
        "dificultad": 'avanzado',
    },
    {
        "id": 225, "rama": 'constitucional', "subtema": 'Garantías Constitucionales',
        "titulo": 'Igualdad ante la ley y no discriminación arbitraria',
        "hechos": 'Una empresa privada se niega a contratar a personas con tatuajes visibles. Un postulante rechazado alega discriminación.',
        "pregunta": '¿Constituye una vulneración al principio de igualdad? ¿Qué normas aplican?',
        "respuesta": 'El art. 19 N°2 CPR garantiza la igualdad ante la ley y prohíbe las diferencias arbitrarias. La Ley 20.609 (Ley Zamudio) prohíbe la discriminación arbitraria en actividades como el trabajo. Tener tatuajes no es una categoría sospechosa de discriminación (raza, sexo, religión, etc.) pero si la distinción es arbitraria —sin causa razonable— puede ser ilegal. El postulante puede interponer acción de no discriminación ante el Juzgado de Letras (art. 3 Ley 20.609). El tribunal evaluará si la exigencia tiene justificación objetiva. Si la empresa aplica la política solo a ciertos grupos protegidos, el caso se refuerza.',
        "fundamento": 'Art. 19 N°2 CPR; Ley 20.609 arts. 1, 3',
        "dificultad": 'intermedio',
    },
    {
        "id": 226, "rama": 'laboral', "subtema": 'Contrato de Trabajo',
        "titulo": 'Modificación unilateral de funciones: el ius variandi',
        "hechos": 'María fue contratada como secretaria. El empleador le asignó funciones de aseo y limpieza, argumentando necesidades de la empresa. María rechaza el cambio.',
        "pregunta": '¿Puede el empleador modificar unilateralmente las funciones? ¿Cuáles son los límites del ius variandi?',
        "respuesta": 'El ius variandi (art. 12 CT) permite al empleador alterar la naturaleza de los servicios o el sitio en que han de prestarse, con las siguientes limitaciones: (1) las funciones deben ser similares; (2) el sitio de trabajo debe estar en la misma ciudad o localidad; (3) no puede disminuirse la remuneración ni perjudicarse al trabajador. Cambiar de secretaria a asistente de aseo implica una alteración sustancial de la naturaleza de los servicios y posiblemente de la remuneración, excediendo los límites del ius variandi. María puede reclamar ante el Inspector del Trabajo o demandar en el Juzgado Laboral dentro de 30 días (art. 12 inc. 3 CT).',
        "fundamento": 'Art. 12 CT',
        "dificultad": 'básico',
    },
    {
        "id": 227, "rama": 'laboral', "subtema": 'Terminación del Contrato',
        "titulo": 'Despido injustificado y tutela laboral',
        "hechos": 'Carlos, dirigente sindical, fue despedido invocando necesidades de la empresa. Alega que fue despedido por su actividad sindical.',
        "pregunta": '¿Qué protección especial tiene Carlos como dirigente sindical? ¿Qué acciones puede ejercer?',
        "respuesta": 'Los dirigentes sindicales gozan de fuero laboral (art. 224 CT): no pueden ser despedidos salvo autorización judicial por causa legal (desafuero). Si el empleador despide a un dirigente amparado por fuero sin autorización judicial, el despido es nulo y el trabajador debe ser reintegrado o indemnizado en conformidad a lo que determine el juez (art. 174 CT). Además, si el despido obedece a la actividad sindical, procede la tutela de derechos fundamentales (art. 485 CT) por vulneración del derecho a la libertad sindical (art. 19 N°19 CPR). La tutela puede obtener reintegro, indemnización adicional de hasta 11 remuneraciones y medidas de reparación.',
        "fundamento": 'Arts. 174, 224, 485-495 CT; art. 19 N°19 CPR',
        "dificultad": 'avanzado',
    },
    {
        "id": 228, "rama": 'laboral', "subtema": 'Terminación del Contrato',
        "titulo": 'Causal de despido: conductas indebidas del trabajador',
        "hechos": 'Felipe fue sorprendido robando materiales de la empresa por valor de $50.000. El empleador le despide invocando el art. 160 N°1 letra a) CT.',
        "pregunta": '¿Es justificada la causal? ¿Qué exigencias probatorias hay para el empleador?',
        "respuesta": 'El art. 160 N°1 letra a) CT permite el despido por conducta inmoral o actos reñidos con la buena fe que afecten el trabajo (incluido el hurto o robo). Esta causal no da derecho a indemnización. El empleador debe: (1) invocar la causal por escrito en la carta de despido indicando los hechos en que se funda; (2) probar los hechos en juicio si el trabajador impugna el despido. El Juzgado Laboral puede declarar el despido justificado o injustificado. Si no se prueba la causal, se convierte en despido injustificado con derecho a indemnización. El plazo para pagar las prestaciones es el día del despido.',
        "fundamento": 'Arts. 159, 160, 162, 168 CT',
        "dificultad": 'básico',
    },
    {
        "id": 229, "rama": 'laboral', "subtema": 'Remuneraciones',
        "titulo": 'Horas extraordinarias: requisitos y pago',
        "hechos": 'La empresa exige a sus empleados trabajar 50 horas semanales (jornada ordinaria es 45 horas) sin pagar horas extra. Alegan que se paga todo con el sueldo mensual.',
        "pregunta": '¿Tiene el empleador obligación de pagar horas extra? ¿Cómo se calculan?',
        "respuesta": 'La jornada ordinaria máxima es de 45 horas semanales (art. 22 CT). Las horas trabajadas sobre dicho límite son extraordinarias (art. 30 CT) y deben pactarse por escrito. Se pagan con un recargo mínimo del 50% sobre el sueldo convenido para la jornada ordinaria (art. 32 CT). El pacto de horas extra solo puede referirse a situaciones temporales y no puede exceder 2 horas diarias ni 12 horas semanales. Pactar que el sueldo mensual incluye las horas extra es inválido si no se especifica la cantidad y el valor. Los trabajadores pueden reclamar ante la Inspección del Trabajo y demandar en el Juzgado Laboral con plazo de 2 años.',
        "fundamento": 'Arts. 22, 30, 32 CT',
        "dificultad": 'básico',
    },
    {
        "id": 230, "rama": 'laboral', "subtema": 'Accidentes del Trabajo',
        "titulo": 'Responsabilidad del empleador en accidente laboral',
        "hechos": 'Un trabajador de construcción cayó desde un andamio sin arnés de seguridad. La empresa no había implementado las medidas de seguridad exigidas por ley.',
        "pregunta": '¿Qué responsabilidad tiene el empleador? ¿Bajo qué estatutos?',
        "respuesta": 'El empleador responde bajo dos estatutos: (1) Ley 16.744 de accidentes del trabajo: el trabajador tiene derecho a prestaciones médicas, subsidio por incapacidad, pensión de invalidez y, en caso de muerte, pensión de sobrevivencia para su familia; (2) responsabilidad civil extracontractual si la empresa incurrió en culpa o negligencia grave al no proporcionar los elementos de protección personal (art. 184 CT: deber de seguridad del empleador). Si el accidente se debió a negligencia de la empresa, los familiares pueden demandar indemnización por daño moral y material, adicional a las prestaciones de la Ley 16.744.',
        "fundamento": 'Art. 184 CT; Ley 16.744 arts. 5, 69',
        "dificultad": 'avanzado',
    },
    {
        "id": 231, "rama": 'civil', "subtema": 'Derecho de Familia',
        "titulo": 'Divorcio por cese de convivencia unilateral',
        "hechos": 'Jorge y Carmen llevan separados de hecho 3 años sin acuerdo de divorcio. Carmen quiere divorciarse pero Jorge se niega. No tienen hijos en común.',
        "pregunta": '¿Puede Carmen obtener el divorcio sin el consentimiento de Jorge? ¿Qué plazo se requiere?',
        "respuesta": 'Sí. El art. 55 inc. 3 LMC establece el divorcio por cese de convivencia: cualquiera de los cónyuges puede demandar el divorcio si han cesado la convivencia por un lapso de 3 años. Carmen puede presentar la demanda de divorcio unilateral ante el Tribunal de Familia. Debe acreditar el cese de la convivencia mediante cualquier medio probatorio (testigos, escritura, etc.). Jorge no puede oponerse al divorcio una vez cumplido el plazo legal. El tribunal solo verificará que se acredite el cese de convivencia. El divorcio produce la terminación del matrimonio y de la sociedad conyugal.',
        "fundamento": 'Arts. 53, 55 LMC; art. 19 LMC',
        "dificultad": 'básico',
    },
    {
        "id": 232, "rama": 'civil', "subtema": 'Derecho de Familia',
        "titulo": 'Violencia intrafamiliar: medidas cautelares',
        "hechos": 'Ana denuncia que su cónyuge la ha golpeado reiteradamente. Teme que al volver a casa el agresor la lastime de nuevo. Quiere protección urgente.',
        "pregunta": '¿Qué medidas urgentes puede solicitar Ana? ¿Qué tribunal es competente?',
        "respuesta": 'El Tribunal de Familia es competente para conocer la violencia intrafamiliar (Ley 20.066). Puede dictar de manera urgente medidas cautelares (art. 92 LTF): (1) prohibición de acercarse a la víctima; (2) salida del agresor del hogar; (3) prohibición de porte de armas; (4) fijación provisional de alimentos, tuición y visitas. La denuncia también puede hacerse ante Carabineros, quienes pueden tomar medidas de protección de inmediato (art. 7 Ley 20.066). Paralelamente, si hay lesiones, puede interponerse denuncia penal por el delito de lesiones o violencia intrafamiliar ante el Ministerio Público.',
        "fundamento": 'Ley 20.066; Ley 19.968 art. 92',
        "dificultad": 'básico',
    },
    {
        "id": 233, "rama": 'civil', "subtema": 'Derecho de Familia',
        "titulo": 'Cuidado personal compartido de los hijos',
        "hechos": 'Tras el divorcio de sus padres, los hijos de 8 y 10 años viven con la madre. El padre, que tiene igual idoneidad parental, solicita que se establezca cuidado personal compartido.',
        "pregunta": '¿Procede el cuidado personal compartido? ¿Qué debe probar el padre?',
        "respuesta": 'Sí. La Ley 20.680 incorporó el cuidado personal compartido como modalidad en Chile (art. 225 CC). El juez puede fijarlo cuando ambos padres tengan condiciones adecuadas y sea en el mejor interés del hijo. No es la regla general ni requiere acuerdo, puede ser fijado por el tribunal a petición de parte. El padre debe acreditar: (1) idoneidad parental; (2) disposición a fomentar la relación del hijo con la madre; (3) que el cuidado compartido es beneficioso para el bienestar del menor. El juez evalúa el interés superior del niño como principio rector (art. 222 CC y Convención ONU sobre los Derechos del Niño).',
        "fundamento": 'Arts. 222, 225 CC; Ley 20.680',
        "dificultad": 'intermedio',
    },
    {
        "id": 234, "rama": 'civil', "subtema": 'Derecho de Familia',
        "titulo": 'Sociedad conyugal: bienes propios y sociales',
        "hechos": 'María recibió en herencia una casa durante el matrimonio. Con dinero de las rentas del hogar compró un auto. Al divorciarse, María quiere saber qué bienes son suyos.',
        "pregunta": '¿Son la casa y el auto bienes propios o sociales? ¿Cómo se determina?',
        "respuesta": 'En la sociedad conyugal, los bienes adquiridos a título gratuito (herencia, donación, legado) durante el matrimonio son bienes propios del cónyuge que los recibe (art. 1726 CC). La casa heredada es bien propio de María. El auto comprado con dinero de las rentas del hogar (que son frutos civiles de los bienes comunes o del trabajo conyugal) forma parte del haber social (art. 1725 CC). Por tanto: la casa es bien propio de María y le pertenece exclusivamente; el auto es bien social y se divide por mitades en la liquidación. María debe solicitar la disolución y liquidación de la sociedad conyugal.',
        "fundamento": 'Arts. 1725, 1726, 1732, 1760 CC',
        "dificultad": 'avanzado',
    },
    {
        "id": 235, "rama": 'civil', "subtema": 'Derecho de Familia',
        "titulo": 'Filiación: acción de reclamación por el hijo',
        "hechos": 'Rodrigo, de 25 años, desconoce a su padre biológico. Descubrió que Jorge podría serlo. Quiere demandar el reconocimiento de la filiación.',
        "pregunta": '¿Tiene Rodrigo acción de reclamación de filiación? ¿Prescribe esta acción?',
        "respuesta": 'Sí. El art. 205 CC otorga al hijo la acción de reclamación de filiación no matrimonial contra su padre o madre. Rodrigo puede demandar a Jorge en el Tribunal de Familia, quien puede decretar la práctica de examen de ADN como prueba pericial. La acción de reclamación de filiación es imprescriptible para el hijo (art. 195 CC): puede ejercerse en cualquier momento durante la vida del hijo. La prueba del ADN tiene valor probatorio pleno para establecer la filiación. Si el demandado se niega al examen, se puede presumir la filiación. Establecida judicialmente, produce todos los efectos civiles: apellido, herencia, alimentos.',
        "fundamento": 'Arts. 195, 205-208, 212 CC',
        "dificultad": 'básico',
    },
    {
        "id": 236, "rama": 'civil', "subtema": 'Derecho Sucesorio',
        "titulo": 'Asignaciones forzosas: legítima rigorosa',
        "hechos": 'Pedro dejó testamento en el que solo legó sus bienes a su pareja, excluyendo totalmente a sus tres hijos. Sus hijos quieren reclamar su parte.',
        "pregunta": '¿Pueden los hijos reclamar una parte de la herencia? ¿Cuánto corresponde a cada uno?',
        "respuesta": 'Los hijos son legitimarios (asignatarios forzosos) que tienen derecho a la legítima (art. 1167 CC). La mitad legitimaria se divide por partes iguales entre los hijos (art. 1184 CC). Con tres hijos, la mitad legitimaria corresponde al 50% de la herencia, dividida en tres partes iguales (16,67% cada uno). Además, hay una cuarta de mejoras (que puede dejarse a algún legitimario privilegiado) y una cuarta de libre disposición (que puede legarse a quien sea). Si el testamento ignora las legítimas, los hijos tienen acción de reforma del testamento (art. 1216 CC) para que se complete su legítima. El plazo es de 4 años desde la apertura de la sucesión.',
        "fundamento": 'Arts. 1167, 1184, 1190, 1216 CC',
        "dificultad": 'intermedio',
    },
    {
        "id": 237, "rama": 'civil', "subtema": 'Derecho Sucesorio',
        "titulo": 'Indignidad para suceder',
        "hechos": 'Juan fue condenado por homicidio de su madre. Al morir su abuelo (padre de la madre), Juan quiere heredar en representación de su madre.',
        "pregunta": '¿Puede Juan heredar? ¿Qué es la indignidad para suceder?',
        "respuesta": 'La indignidad para suceder implica que ciertas personas, por sus actos, son privadas del derecho a heredar (art. 968 CC). Una de las causales de indignidad es haber cometido homicidio en la persona del causante o de un ascendiente, descendiente o cónyuge del causante (art. 968 N°1 CC). Si Juan mató a su madre (ascendiente del abuelo), podría quedar afecto a indignidad para heredar del abuelo. La indignidad debe ser declarada judicialmente y alegada por los interesados. Si se declara, Juan pierde su derecho herencial. Los herederos que alegan la indignidad tienen la carga de probarla.',
        "fundamento": 'Arts. 968-972 CC; Abeliuk, Sucesorio',
        "dificultad": 'avanzado',
    },
    {
        "id": 238, "rama": 'civil', "subtema": 'Derecho Sucesorio',
        "titulo": 'Posesión efectiva y trámites sucesorios',
        "hechos": 'Falleció Ana, quien tenía bienes raíces a su nombre. Sus hijos quieren inscribir los inmuebles a su nombre. No hay testamento.',
        "pregunta": '¿Qué trámites deben seguir los herederos? ¿Dónde se tramita la posesión efectiva?',
        "respuesta": 'Los herederos deben seguir el procedimiento de posesión efectiva para legitimar su calidad de herederos y poder disponer de los bienes. Para sucesiones intestadas, la posesión efectiva se tramita ante el Registro Civil (Ley 19.903). Los herederos presentan la solicitud con el RUT del causante, certificado de defunción y antecedentes que acrediten la calidad de herederos. El Registro Civil publica un extracto, luego dicta la resolución de posesión efectiva. Con esta resolución y el inventario solemne, los herederos pueden inscribir los inmuebles en el Conservador. También deben pagar el Impuesto a la Herencia según la Ley 16.271.',
        "fundamento": 'Arts. 688, 956 CC; Ley 19.903; Ley 16.271',
        "dificultad": 'básico',
    },
    {
        "id": 239, "rama": 'civil', "subtema": 'Derecho Sucesorio',
        "titulo": 'Testamento solemne abierto: requisitos de validez',
        "hechos": 'Don Roberto otorgó testamento ante notario y tres testigos. Uno de los testigos es empleado del notario. Fallecido Roberto, un heredero impugna el testamento.',
        "pregunta": '¿Tiene validez el testamento? ¿Cuáles son las inhabilidades de testigos?',
        "respuesta": 'El testamento solemne abierto requiere, conforme al art. 1014 CC: otorgarse ante competente notario y tres testigos hábiles. El art. 1012 CC establece las inhabilidades de testigos: entre ellas, son inhábiles los dependientes o asalariados del notario autorizante (art. 1012 N°7 CC). Si el testigo es empleado del notario, incurre en inhabilidad. Un testigo inhábil invalida el testamento si sin él no queda el número mínimo de testigos hábiles (art. 1016 CC). Con solo dos testigos hábiles, el testamento adolece de nulidad. La acción de nulidad testamentaria prescribe en 4 años desde que el heredero supo del testamento.',
        "fundamento": 'Arts. 1007, 1012, 1014, 1016 CC',
        "dificultad": 'avanzado',
    },
    {
        "id": 240, "rama": 'civil', "subtema": 'Derecho Sucesorio',
        "titulo": 'Colación de donaciones en vida del causante',
        "hechos": 'El causante donó en vida a uno de sus tres hijos un inmueble valorado en $100 millones. Al morir, el patrimonio restante es de $200 millones. Los otros hijos exigen igualdad.',
        "pregunta": '¿Deben imputarse las donaciones a la herencia? ¿Qué es la colación?',
        "respuesta": 'La colación (art. 1198 CC) es la obligación de ciertos herederos de imputar a su cuota hereditaria lo que han recibido del causante por donaciones en vida. Los descendientes legitimarios que han recibido donaciones deben colacionar (devolver ficticiamente al acervo) lo recibido para calcular las legítimas. El inmueble de $100M se agrega al acervo imaginario ($200M + $100M = $300M). Cada hijo tiene derecho a $50M de la mitad legitimaria ($150M / 3). El hijo donatario ya recibió $100M, que excede su cuota de $50M, debiendo restituir el exceso. Los otros hijos reciben $50M cada uno. Así se garantiza la igualdad entre los legitimarios.',
        "fundamento": 'Arts. 1185-1197, 1198 CC; Abeliuk, Sucesorio T.I',
        "dificultad": 'avanzado',
    },
    {
        "id": 241, "rama": 'comercial', "subtema": 'Sociedades',
        "titulo": 'Sociedad anónima: responsabilidad de los accionistas',
        "hechos": 'La sociedad anónima XYZ tiene deudas impagables. Sus accionistas, que tienen el 100% de las acciones, son demandados personalmente por los acreedores de la sociedad.',
        "pregunta": '¿Pueden los acreedores cobrar directamente a los accionistas? ¿Cuál es el principio de separación patrimonial?',
        "respuesta": 'La sociedad anónima (SA) tiene personalidad jurídica propia y patrimonio separado del de sus accionistas. El art. 1 Ley 18.046 dispone que los accionistas responden hasta el monto de sus acciones suscritas y pagadas, sin responder con su patrimonio personal por las deudas sociales. Este es el principio de responsabilidad limitada. Los acreedores solo pueden perseguir el patrimonio de la sociedad, no el personal de los accionistas. Solo excepcionalmente, si hubo fraude, simulación o abuso de la personalidad jurídica, puede levantarse el velo corporativo (doctrina del disregard), pero es de aplicación restrictiva en Chile.',
        "fundamento": 'Ley 18.046 art. 1; Código de Comercio arts. 425 ss.',
        "dificultad": 'básico',
    },
    {
        "id": 242, "rama": 'comercial', "subtema": 'Títulos de Crédito',
        "titulo": 'Letra de cambio: responsabilidad del aval',
        "hechos": 'Banco ABC cobró a Diego una letra de cambio. Diego la firmó como aval del deudor principal, quien es insolvente. Diego alega que primero deben cobrarle al deudor principal.',
        "pregunta": '¿Puede el banco cobrar directamente al aval? ¿Es subsidiaria la responsabilidad del aval?',
        "respuesta": 'No. El aval en una letra de cambio es solidario con el aceptante (deudor principal), conforme al art. 47 Ley 18.092. El banco puede demandar directamente al avalista sin necesidad de perseguir primero al deudor principal. No existe beneficio de excusión (cobrar primero al deudor antes que al garante) en los títulos de crédito. El aval cambiario es una garantía autónoma que obliga al avalista en forma directa. Diego debe pagar la letra y luego tiene acción de reembolso contra el deudor principal (art. 82 Ley 18.092).',
        "fundamento": 'Ley 18.092 arts. 46, 47, 82',
        "dificultad": 'intermedio',
    },
    {
        "id": 243, "rama": 'comercial', "subtema": 'Contratos Mercantiles',
        "titulo": 'Contrato de seguro: deber de declaración del riesgo',
        "hechos": 'Al contratar un seguro de salud, Ana no informó que tenía diabetes tipo 2 diagnosticada. Al reclamar una prestación, la aseguradora alega reticencia y niega el pago.',
        "pregunta": '¿Puede la aseguradora rechazar el siniestro por reticencia? ¿Cuáles son sus derechos?',
        "respuesta": 'La reticencia es la omisión de hechos relevantes que el asegurado conocía y debía declarar al contratar el seguro. El art. 525 Código de Comercio (modificado por Ley 20.667) regula el contrato de seguro. Si el asegurado incurre en reticencia que influye en la evaluación del riesgo, la aseguradora puede rescindir el contrato (dolo o culpa grave) o cobrar la diferencia de prima si la reticencia fue de buena fe. La aseguradora puede rechazar el siniestro si prueba que de haber conocido la enfermedad no habría contratado el seguro o lo habría hecho en condiciones distintas. En salud rigen además normas especiales de la Superintendencia de Salud.',
        "fundamento": 'Arts. 524, 525 CCo; Ley 20.667',
        "dificultad": 'avanzado',
    },
    {
        "id": 244, "rama": 'comercial', "subtema": 'Derecho Concursal',
        "titulo": 'Liquidación voluntaria de empresa',
        "hechos": 'La empresa ABC SpA tiene deudas por $500 millones y activos por solo $200 millones. Los socios quieren acogerse a la Ley 20.720 para liquidar ordenadamente.',
        "pregunta": '¿Qué procedimiento aplica? ¿Qué ocurre con los contratos vigentes?',
        "respuesta": 'La Ley 20.720 de Insolvencia y Reemprendimiento establece el procedimiento de liquidación voluntaria (art. 115 Ley 20.720): la empresa deudora puede solicitar su propia liquidación ante el tribunal competente. Se nombra un liquidador que administra el activo y paga a los acreedores según su preferencia. Los contratos vigentes pueden ser continuados o terminados según lo estime el liquidador (art. 146 Ley 20.720). Los trabajadores tienen preferencia de primer grado en el pago de sus créditos laborales. Al término, si los activos no alcanzaron para pagar todas las deudas, se extinguen los saldos insolutos.',
        "fundamento": 'Ley 20.720 arts. 2, 115, 140, 146',
        "dificultad": 'avanzado',
    },
    {
        "id": 245, "rama": 'comercial', "subtema": 'Contratos Mercantiles',
        "titulo": 'Franquicia comercial: naturaleza y obligaciones',
        "hechos": 'Pedro firmó un contrato de franquicia para operar una tienda de ropa. La franquiciante le exige exclusividad territorial, pago de regalías y seguir estándares de la marca. Pedro quiere retirarse anticipadamente.',
        "pregunta": '¿Qué tipo de contrato es la franquicia? ¿Puede Pedro retirarse sin responsabilidad?',
        "respuesta": 'La franquicia comercial es un contrato atípico (no regulado expresamente en el Código de Comercio chileno) pero válido conforme a la autonomía contractual (art. 1545 CC). Se rige por sus propias cláusulas y supletoriamente por las normas del mandato, arrendamiento de servicios y otros contratos típicos. Pedro tiene obligaciones contractuales de duración determinada. Si se retira anticipadamente sin causal, incurre en incumplimiento contractual y debe indemnizar perjuicios. La cláusula de exclusividad es válida. Las regalías son parte esencial del contrato. Para retirarse sin responsabilidad debe acreditar incumplimiento del franquiciante.',
        "fundamento": 'Art. 1545 CC; Código de Comercio',
        "dificultad": 'intermedio',
    },
    {
        "id": 246, "rama": 'procesal', "subtema": 'Proceso Penal',
        "titulo": 'Prisión preventiva: requisitos y proporcionalidad',
        "hechos": 'Jorge es imputado por robo con violencia. El fiscal solicita prisión preventiva. La defensa alega que tiene domicilio fijo, trabajo estable y sin antecedentes previos.',
        "pregunta": '¿Procede la prisión preventiva? ¿Cuáles son los requisitos legales?',
        "respuesta": 'La prisión preventiva (art. 140 CPP) requiere: (1) antecedentes que justifiquen la existencia del delito; (2) antecedentes que permitan estimar que el imputado ha tenido participación; (3) que la medida sea necesaria para los fines del procedimiento: peligro de fuga, obstaculización de la investigación o peligro para la seguridad de la sociedad o de la víctima. Es la medida más gravosa y debe ser proporcional y subsidiaria. El domicilio fijo y el trabajo estable son factores que atenúan el peligro de fuga. La defensa puede ofrecer medidas cautelares alternativas (arraigo, firma periódica) conforme al art. 155 CPP.',
        "fundamento": 'Arts. 122, 139, 140, 155 CPP',
        "dificultad": 'intermedio',
    },
    {
        "id": 247, "rama": 'procesal', "subtema": 'Proceso Penal',
        "titulo": 'Principio de oportunidad y salidas alternativas',
        "hechos": 'Carlos fue sorprendido con 5 gramos de marihuana para consumo personal. El fiscal quiere aplicar el principio de oportunidad.',
        "pregunta": '¿En qué consiste el principio de oportunidad? ¿Cuáles son sus requisitos y efectos?',
        "respuesta": 'El principio de oportunidad (art. 170 CPP) permite al fiscal no iniciar la persecución penal o abandonarla cuando el hecho no comprometa gravemente el interés público. Requisitos: (1) delito que no tenga pena de crimen; (2) que el imputado no sea funcionario público en ejercicio de sus funciones; (3) que el interés público no esté comprometido gravemente. El fiscal comunica la decisión al imputado e intervinientes. La víctima puede oponerse en 10 días. Si no hay oposición, se extingue la acción penal. Si hay acuerdo reparatorio u otra salida alternativa (suspensión condicional), se evita el juicio oral.',
        "fundamento": 'Arts. 170, 237, 241 CPP',
        "dificultad": 'básico',
    },
    {
        "id": 248, "rama": 'procesal', "subtema": 'Proceso Penal',
        "titulo": 'Acuerdo reparatorio: naturaleza y procedencia',
        "hechos": 'Ana atropelló por descuido al ciclista Pedro, causándole lesiones leves. Pedro acepta recibir $2 millones como reparación integral. La fiscalía quiere saber si procede el acuerdo.',
        "pregunta": '¿Procede el acuerdo reparatorio en este caso? ¿Qué efecto tiene sobre la acción penal?',
        "respuesta": 'El acuerdo reparatorio (art. 241 CPP) procede en: (1) delitos que afectan bienes jurídicos disponibles de carácter patrimonial; (2) lesiones menos graves; (3) delitos culposos. Las lesiones por accidente de tránsito (culpa) y su carácter leve hacen procedente el acuerdo. El juez de garantía lo aprueba verificando que el consentimiento sea libre y conozcan sus derechos. Una vez cumplido el acuerdo, se extingue la acción penal respecto del imputado (art. 242 CPP). No procede si existe un interés público prevalente o si el imputado ha incumplido acuerdos anteriores.',
        "fundamento": 'Arts. 241, 242 CPP',
        "dificultad": 'básico',
    },
    {
        "id": 249, "rama": 'procesal', "subtema": 'Proceso Penal',
        "titulo": 'Juicio oral: principios del debate y valoración de la prueba',
        "hechos": 'En un juicio oral por homicidio, la defensa objeta la declaración de un testigo que en la audiencia preliminar declaró haber visto al acusado, pero que ahora declara no recordar nada.',
        "pregunta": '¿Cómo valora el tribunal la prueba contradictoria? ¿Qué principios rigen la prueba en el juicio oral?',
        "respuesta": 'El juicio oral se rige por los principios de inmediación, oralidad, publicidad y continuidad (art. 282 CPP). La valoración de la prueba es libre conforme a la sana crítica (art. 297 CPP): el tribunal valora la prueba con libertad pero debe hacerlo respetando los principios lógicos, las máximas de la experiencia y los conocimientos científicamente afianzados. Frente a un testigo que contradice su declaración previa, la parte puede solicitar que se lean sus declaraciones anteriores para efectos de impugnar su credibilidad (art. 332 CPP). El tribunal evalúa la credibilidad del testigo considerando todas las circunstancias.',
        "fundamento": 'Arts. 282, 295, 296, 297, 332 CPP; Accatino, Certezas y Dudas',
        "dificultad": 'avanzado',
    },
    {
        "id": 250, "rama": 'procesal', "subtema": 'Proceso Penal',
        "titulo": 'Recurso de nulidad penal: causales',
        "hechos": 'El condenado alega que durante el juicio oral se incorporó prueba ilícita obtenida sin orden judicial (grabación de llamadas telefónicas), lo que determinó su condena.',
        "pregunta": '¿Qué recurso procede? ¿Cuál es la causal aplicable?',
        "respuesta": 'Procede el recurso de nulidad (art. 372 CPP), el recurso ordinario contra la sentencia del juicio oral. La causal aplicable es el art. 373 letra a) CPP: cuando la sentencia se ha pronunciado con infracción sustancial de derechos o garantías asegurados por la Constitución o tratados internacionales ratificados por Chile. La incorporación de prueba ilícita (grabación sin orden judicial) vulnera el art. 19 N°5 CPR (inviolabilidad de comunicaciones privadas) y el art. 9 CPP (que exige autorización judicial para actos que afecten garantías fundamentales). El tribunal ad quem puede anular la sentencia y el juicio, ordenando nuevo juicio oral.',
        "fundamento": 'Arts. 372, 373, 374 CPP; art. 19 N°5 CPR',
        "dificultad": 'avanzado',
    },
]